import { ReactNode } from "react";
import { AiOutlineMail } from "react-icons/ai";
import { IoCallOutline, IoLocationOutline } from "react-icons/io5";
export { default as BuyRent } from "@/app/components/BuyRent";
export { default as ClientsStories } from "@/app/components/ClientsStories";
export { default as Email } from "@/app/components/Email";
export { default as Footer } from "@/app/components/Footer";
export { default as GridDiv } from "@/app/components/GridDiv";
export { default as Hero } from "@/app/components/Hero";
export { default as MainPages } from "@/app/components/MainPages";
export { default as NavBar } from "@/app/components/NavBar";
export { default as Rent } from "@/app/components/Rent";
export { default as Sale } from "@/app/components/Sale";
export { default as TeamCard } from "@/app/components/TeamCard";
export const stories = [
  {
    writer: "Sarah & Jake M.",
    story:
      "As first-time homebuyers, we were nervous about the process, but AK made everything so easy! They took the time to explain every detail, guided us through each step, and found us the perfect home in our budget. We couldn’t be happier!",
  },
  {
    writer: "James R.",
    story:
      "Selling a home can be stressful, but AK turned it into a breeze. From staging advice to professional photos and expert marketing, my house sold in just 10 days for above the asking price. I highly recommend their services!",
  },
  {
    writer: "Laura T.",
    story:
      "Moving across the country felt overwhelming, but Ak went above and beyond to help us find a home that met all our needs. Their virtual tours, neighborhood insights, and prompt responses made the process smooth and enjoyable. We’re so grateful!",
  },
  {
    writer: "Michael P.",
    story:
      "I was looking for a great investment property, and AK was incredibly knowledgeable about the market. They helped me find a rental property with excellent ROI, and the closing process was seamless. I look forward to working with them again!",
  },
  {
    writer: "The Johnson Family",
    story:
      "We had a very specific vision for our dream home, and Ak went above and beyond to find it. They were patient, attentive, and always had our best interests at heart. Now we’re living in the home we’ve always dreamed of, thanks to their expertise!",
  },
];
export const contact: {
  icon: ReactNode;
  bold: string;
  text1: string;
  text2: string;
}[] = [
  {
    icon: <IoCallOutline color="red" size={60} />,
    bold: "Call Us",
    text1: "Free Calls",
    text2: "1-800-000-000",
  },
  {
    icon: <IoLocationOutline color="red" size={60} />,
    bold: "Find Us",
    text1: "500 Terry Francine St.",
    text2: "San Francisco, CA 94158",
  },
  {
    icon: <AiOutlineMail color="red" size={60} />,
    bold: "Email Us",
    text1: "Direct Email",
    text2: "info@mysite.com",
  },
];
export const realtors = [
  {
    name: "Gregory Jems",
    img: "/one.avif",
  },
  {
    name: "Britney Bails",
    img: "/two.avif",
  },
  {
    name: "Gerry Grossman",
    img: "/three.avif",
  },
  {
    name: "Don White",
    img: "/four.avif",
  },
  {
    name: "Brenda Rogers",
    img: "/five.avif",
  },
  {
    name: "Mike Helman",
    img: "/six.avif",
  },
];
export const Properties = [
  {
    id: 1,
    location: "17081 Perry",
    city: "San Francisco, CA, USA",
    price: "$850,000",
    img: "/project_img_1.jpg",
    baths: 3,
    beds: 2,
    levels: 4,
    sqft: 1234,
    imgText: "BUY",
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 2,
    location: "52591 Union Boulevard",
    city: "San Francisco, CA, USA",
    price: "$580,000",
    img: "/project_img_2.jpg",
    baths: 2,
    beds: 3,
    levels: 4,
    imgText: "BUY",

    sqft: 1546,
    realtor: { name: "Don White", img: "/four.avif" },
  },
  {
    id: 3,
    location: "15066 Banks Street",
    city: "San Francisco, CA, USA",
    price: "$700,000",
    img: "/project_img_3.jpg",
    baths: 2,
    beds: 3,
    levels: 2,
    imgText: "BUY",

    sqft: 1090,
    realtor: { name: "Gregory Jems", img: "/one.avif" },
  },
  {
    id: 4,
    location: "33234 Washington Avenue",
    city: "San Francisco, CA, USA",
    price: "$770,000",
    img: "/project_img_4.jpg",
    baths: 1,
    beds: 3,
    levels: 2,
    imgText: "BUY",

    sqft: 900,
    realtor: { name: "Brenda Rogers", img: "/five.avif" },
  },
  {
    id: 5,
    location: "442 East Main Street",
    city: "Austin, TX, USA",
    price: "$450,000",
    img: "/project_img_5.jpg",
    baths: 2,
    imgText: "BUY",

    beds: 2,
    levels: 1,
    sqft: 1400,
    realtor: { name: "Gerry Grossman", img: "/three.avif" },
  },
  {
    id: 6,
    location: "300 West Elm Street",
    city: "Denver, CO, USA",
    price: "$630,000",
    img: "/project_img_6.jpg",
    baths: 3,
    beds: 3,
    imgText: "BUY",

    levels: 2,
    sqft: 1850,
    realtor: { name: "Mike Helman", img: "/six.avif" },
  },
  {
    id: 7,
    location: "92 Pine Road",
    city: "Seattle, WA, USA",
    price: "$750,000",
    img: "/project_img_7.jpg",
    baths: 2,
    beds: 3,
    imgText: "BUY",

    levels: 2,
    sqft: 1600,
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 8,
    location: "1806 Maple Avenue",
    city: "Chicago, IL, USA",
    price: "$520,000",
    img: "/project_img_8.jpg",
    baths: 2,
    beds: 2,
    imgText: "BUY",

    levels: 3,
    sqft: 1250,
    realtor: { name: "Gregory Jems", img: "/one.avif" },
  },
  {
    id: 9,
    location: "1029 Hilltop Drive",
    city: "Nashville, TN, USA",
    price: "$400,000",
    img: "/project_img_9.jpg",
    baths: 2,
    beds: 3,
    imgText: "BUY",

    levels: 1,
    sqft: 1350,
    realtor: { name: "Brenda Rogers", img: "/five.avif" },
  },
  {
    id: 10,
    location: "317 Coastal Avenue",
    city: "Miami, FL, USA",
    price: "$950,000",
    img: "/project_img_10.jpg",
    baths: 4,
    beds: 4,
    imgText: "BUY",

    levels: 3,
    sqft: 2100,
    realtor: { name: "Gerry Grossman", img: "/three.avif" },
  },
  {
    id: 11,
    location: "245 Sunset Boulevard",
    city: "Los Angeles, CA, USA",
    price: "$1,200,000",
    img: "/project_img_11.jpg",
    baths: 3,
    beds: 4,
    imgText: "BUY",
    levels: 2,
    sqft: 2500,
    realtor: { name: "Don White", img: "/four.avif" },
  },
  {
    id: 12,
    location: "19 Desert Oasis Lane",
    city: "Phoenix, AZ, USA",
    price: "$360,000",
    img: "/project_img_12.jpg",
    baths: 2,
    beds: 2,
    imgText: "RENT",
    levels: 1,
    sqft: 1400,
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 13,
    location: "572 Greenway Drive",
    city: "Orlando, FL, USA",
    price: "$480,000",
    img: "/project_img_13.jpg",
    baths: 2,
    imgText: "RENT",
    beds: 3,
    levels: 1,
    sqft: 1500,
    realtor: { name: "Don White", img: "/four.avif" },
  },
  {
    id: 14,
    location: "80 Maplewood Lane",
    city: "Portland, OR, USA",
    price: "$720,000",
    img: "/project_img_14.jpg",
    baths: 3,
    imgText: "RENT",
    beds: 4,
    levels: 2,
    sqft: 2200,
    realtor: { name: "Mike Helman", img: "/six.avif" },
  },
  {
    id: 15,
    location: "240 Brightview Court",
    city: "Dallas, TX, USA",
    price: "$540,000",
    img: "/project_img_15.jpg",
    baths: 2,
    beds: 3,
    imgText: "RENT",
    levels: 2,
    sqft: 1900,
    realtor: { name: "Brenda Rogers", img: "/five.avif" },
  },
  {
    id: 16,
    location: "101 Redwood Road",
    city: "Salt Lake City, UT, USA",
    price: "$650,000",
    img: "/project_img_16.jpg",
    baths: 3,
    beds: 3,
    imgText: "RENT",
    levels: 3,
    sqft: 1800,
    realtor: { name: "Gregory Jems", img: "/one.avif" },
  },
  {
    id: 17,
    location: "400 Ocean Breeze Avenue",
    city: "San Diego, CA, USA",
    price: "$980,000",
    img: "/project_img_17.jpg",
    baths: 3,
    beds: 4,
    imgText: "RENT",
    levels: 2,
    sqft: 2300,
    realtor: { name: "Gregory Jems", img: "/one.avif" },
  },
  {
    id: 18,
    location: "780 Cherry Blossom Way",
    city: "Charlotte, NC, USA",
    price: "$460,000",
    img: "/project_img_18.jpg",
    baths: 2,
    beds: 3,
    imgText: "RENT",
    levels: 1,
    sqft: 1700,
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 19,
    location: "50 Ridgeview Terrace",
    city: "Raleigh, NC, USA",
    price: "$500,000",
    img: "/project_img_19.jpg",
    baths: 2,
    beds: 4,
    imgText: "RENT",
    levels: 2,
    sqft: 2000,
    realtor: { name: "Brenda Rogers", img: "/five.avif" },
  },
  {
    id: 20,
    location: "2010 Harbor View Drive",
    city: "Newport Beach, CA, USA",
    price: "$1,800,000",
    img: "/project_img_20.jpg",
    baths: 4,
    beds: 5,
    imgText: "RENT",
    levels: 3,
    sqft: 3200,
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 21,
    location: "615 Park Avenue",
    city: "New York, NY, USA",
    price: "$2,500,000",
    img: "/project_img_21.jpg",
    baths: 3,
    beds: 4,
    imgText: "RENT",
    levels: 2,
    sqft: 2500,
    realtor: { name: "Britney Bails", img: "/two.avif" },
  },
  {
    id: 22,
    location: "800 Mountain View Lane",
    city: "Boulder, CO, USA",
    price: "$800,000",
    img: "/project_img_22.jpg",
    baths: 3,
    beds: 3,
    imgText: "RENT",
    levels: 2,
    sqft: 2100,
    realtor: { name: "Gregory Jems", img: "/one.avif" },
  },
  {
    id: 23,
    location: "570 Greenway Drive",
    city: "Orlando, FL, USA",
    price: "$480,000",
    img: "/project_img_13.jpg",
    baths: 2,
    beds: 3,
    imgText: "RENT",
    levels: 1,
    sqft: 1500,
    realtor: {
      name: "Don White",
      img: "/four.avif",
    },
  },
  {
    id: 24,
    location: "88 Maplewood Lane",
    city: "Portland, OR, USA",
    price: "$720,000",
    img: "/project_img_14.jpg",
    baths: 3,
    beds: 4,
    imgText: "RENT",
    levels: 2,
    sqft: 2200,
    realtor: {
      name: "Mike Helman",
      img: "/six.avif",
    },
  },
  {
    id: 25,
    location: "246 Brightview Court",
    city: "Dallas, TX, USA",
    price: "$540,000",
    img: "/project_img_15.jpg",
    baths: 2,
    beds: 3,
    imgText: "RENT",
    levels: 2,
    sqft: 1900,
    realtor: {
      name: "Brenda Rogers",
      img: "/five.avif",
    },
  },
  {
    id: 26,
    location: "103 Redwood Road",
    city: "Salt Lake City, UT, USA",
    price: "$650,000",
    img: "/project_img_16.jpg",
    baths: 3,
    beds: 3,
    imgText: "RENT",
    levels: 3,
    sqft: 1800,
    realtor: {
      name: "Gregory Jems",
      img: "/one.avif",
    },
  },
  {
    id: 27,
    location: "401 Ocean Breeze Avenue",
    city: "San Diego, CA, USA",
    price: "$980,000",
    img: "/project_img_17.jpg",
    baths: 3,
    beds: 4,
    imgText: "RENT",
    levels: 2,
    sqft: 2300,
    realtor: {
      name: "Gregory Jems",
      img: "/one.avif",
    },
  },
  {
    id: 28,
    location: "788 Cherry Blossom Way",
    city: "Charlotte, NC, USA",
    price: "$460,000",
    img: "/project_img_18.jpg",
    baths: 2,
    beds: 3,
    imgText: "RENT",
    levels: 1,
    sqft: 1700,
    realtor: {
      name: "Britney Bails",
      img: "/two.avif",
    },
  },
  {
    id: 29,
    location: "5 Ridgeview Terrace",
    city: "Raleigh, NC, USA",
    price: "$500,000",
    img: "/project_img_19.jpg",
    baths: 2,
    beds: 4,
    imgText: "BUY",
    levels: 2,
    sqft: 2000,
    realtor: {
      name: "Brenda Rogers",
      img: "/five.avif",
    },
  },
  {
    id: 30,
    location: "2009 Harbor View Drive",
    city: "Newport Beach, CA, USA",
    price: "$1,800,000",
    img: "/project_img_20.jpg",
    baths: 4,
    beds: 5,
    imgText: "BUY",
    levels: 3,
    sqft: 3200,
    realtor: {
      name: "Britney Bails",
      img: "/two.avif",
    },
  },
  {
    id: 31,
    location: "614 Park Avenue",
    city: "New York, NY, USA",
    price: "$2,500,000",
    img: "/project_img_21.jpg",
    baths: 3,
    beds: 4,
    imgText: "BUY",
    levels: 2,
    sqft: 2500,
    realtor: {
      name: "Britney Bails",
      img: "/two.avif",
    },
  },
  {
    id: 32,
    location: "900 Mountain View Lane",
    city: "Boulder, CO, USA",
    price: "$800,000",
    img: "/project_img_22.jpg",
    baths: 3,
    beds: 3,
    imgText: "RENT",
    levels: 2,
    sqft: 2100,
    realtor: {
      name: "Gregory Jems",
      img: "/one.avif",
    },
  },
];
export const saleArray = Properties.filter((s) => s.imgText === "BUY");
export const rentArray = Properties.filter((s) => s.imgText === "RENT");
